######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 6 15:13:27 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imgTool.h myWidget.h
SOURCES += imgTool.cpp main.cpp myWidget.cpp
