######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 12 15:35:14 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
