######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 18 21:46:27 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
