######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 22 16:48:21 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imgTool.h myWidget.h
SOURCES += imgTool.cpp main.cpp myWidget.cpp
