######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 1 11:01:05 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Model.h PainterWidget.h
SOURCES += main.cpp Model.cpp PainterWidget.cpp
