main:
	g++ -c bigInt2.cpp -o bigInt2.o
	g++ -c rational.cpp -o rational.o
	g++ -c complex.cpp -o complex.o
	g++ bigInt2.o rational.o complex.o hw5_team15.cpp -o hw5_team15.exe
clean:
	rm -rf bigInt2.o rational.o complex.o hw5_team15.exe
