main:
	g++ -c bigInt.cpp -o bigInt.o
	g++ -c rational.cpp -o rational.o
	g++ -c complex.cpp -o complex.o
	g++ bigInt.o rational.o complex.o hw5_team15.cpp -o hw5_team15.exe
clean:
	rm -rf bigInt.o rational.o complex.o hw5_team15.exe
