######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 09:33:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Model.h PainterWidget.h
SOURCES += main.cpp Model.cpp PainterWidget.cpp
