######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 28 17:08:13 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Model.h PainterWidget.h
SOURCES += main.cpp Model.cpp PainterWidget.cpp
