######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 19 12:04:53 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += getDefectType.h imgTool.h myWidget.h
SOURCES += getDefectType.cpp imgTool.cpp main.cpp myWidget.cpp
