######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 19 02:37:08 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += getDefectType.h imgTool.h myWidget.h
SOURCES += getDefectType.cpp imgTool.cpp main.cpp myWidget.cpp
