main:
	g++ -c BigInt.cpp -o BigInt.o
	g++ -c rational.cpp -o rational.o
	g++ -c complex.cpp -o complex.o
	g++ rational.o complex.o hw5_team15.cpp -o hw5_team15.exe
clean:
	rm -rf BigInt.o rational.o complex.o hw5_team15.exe
