######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 9 15:43:31 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
