######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 20 12:20:41 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += getDefectType.h imgTool.h myWidget.h
SOURCES += getDefectType.cpp imgTool.cpp main.cpp myWidget.cpp
